stages:
  - build
  - update-helm

variables:
  IMAGE_NAME: gitlab.local:5050/root/kim-minji-backend
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

build_and_push:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  tags:
    - arm64
    - docker
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"gitlab.local:5050\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $IMAGE_NAME:$IMAGE_TAG --destination $IMAGE_NAME:latest --insecure --skip-tls-verify
  only:
    - develop
    - main

update-helm:
  stage: update-helm
  image: alpine:latest
  tags:
    - arm64
    - docker
  before_script:
    - apk add --no-cache git curl
    - git config --global user.email "gitlab-ci@gitlab.local"
    - git config --global user.name "GitLab CI"
    - git config --global http.sslVerify false
  script:
    - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@172.18.0.2:8929/root/kim-minji-helm.git
    - cd kim-minji-helm
    - sed -i 's/tag:.*/tag: "'${CI_COMMIT_SHORT_SHA}'"/' backend/values.yaml
    - git add backend/values.yaml
    - git commit -m "ci update backend tag to '${CI_COMMIT_SHORT_SHA}'"
    - git push origin main
  only:
    - main