spring.application.name=codecobain-backend

server.port=8080

# ============== MinIO ============
minio.endpoint=${MINIO_ENDPOINT:http://minio.storage.svc.cluster.local:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin123}
minio.bucket=${MINIO_BUCKET:wafer-image-bucket}

# =============== database ==================
spring.datasource.url=${DB_URL:jdbc:mysql://mysql.storage.svc.cluster.local:3306/appdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:appuser}
spring.datasource.password=${DB_PASSWORD:apppass123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ========= AI server ============
ai.server.url=${AI_SERVER_URL:http://ai-serving-service.ai-serving.svc.cluster.local:8000}
ai.endpoint.predict=/predict

# H2 ???? ????
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.h2.H2ConsoleAutoConfiguration